# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.1.0'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'Art'
    publishLocation: 'pipeline'

#- task: AzureRmWebAppDeployment@4
#  inputs:
#    ConnectionType: 'AzureRM'
#    azureSubscription: 'Pay-As-You-Go(171f5f8c-bcb9-4185-8aaf-60ffbd04f09f)'
#    appType: 'webApp'
#    WebAppName: 'bill-angular'
#    packageForLinux: '$(Pipeline.Workspace)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(3)(171f5f8c-bcb9-4185-8aaf-60ffbd04f09f)'
    appType: 'webApp'
    appName: 'bill-angular'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'



#- task: AzureFileCopy@4
#  inputs:
#    SourcePath: '$(Pipeline.Workspace)'
#    azureSubscription: 'Pay-As-You-Go(171f5f8c-bcb9-4185-8aaf-60ffbd04f09f)'
#    Destination: 'AzureBlob'
#    storage: 'filsharetest'
#    ContainerName: '$web'
#    BlobPrefix: 'light'

#- task: AzureCLI@2
#  inputs:
#    azureSubscription: 'Pay-As-You-Go(1)(171f5f8c-bcb9-4185-8aaf-60ffbd04f09f)'
#    
#    scriptType: bash
#    scriptLocation: 'inlinescript'
#    inlinescript: |
#      az storage blob upload-batch --account-name fdfiles --auth-mode key -d '$web' --source '$(Pipeline.Workspace)' --connection-string 'DefaultEndpointsProtocol=https;AccountName=filsharetest;AccountKey=y/oT2j7u3u8rZDKZ0qVOMWERFH/CRgToXYtsdRbm/tBnhWgm4uWUe1K0/BIOlqJrukiua4rBQAbO+AStP4DrWw==;EndpointSuffix=core.windows.net'


#--destination mycontainer --source <path-to-directory>
